"""Export Service — PDF, CBZ, PPTX, MP4 exports.

The part where all the art becomes a deliverable.
PDFs for comics, CBZ for comic readers, PPTX for pitch decks,
MP4 for trailers. Every format your producer might ask for.
"""

import io
import zipfile
import uuid
from typing import Optional

import httpx
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.utils import ImageReader
from reportlab.platypus import SimpleDocTemplate, Image, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from pptx import Presentation
from pptx.util import Inches, Pt

from app.models.schemas import PanelPage, PanelMetadata, TrailerProject
from app.services.storage import upload_export


async def _download_image(url: str) -> bytes | None:
    """Download an image from URL. Returns None if it fails."""
    if not url:
        return None
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.get(url)
            resp.raise_for_status()
            return resp.content
    except Exception:
        return None


# ── PDF Export ─────────────────────────────────────────────────────────────

async def export_pdf(
    pages: list[PanelPage],
    project_id: str,
    title: str = "StoryForge Pro",
) -> str:
    """Export panels as a PDF document.

    Args:
        pages: List of panel pages.
        project_id: Project ID for storage path.
        title: Document title.

    Returns:
        Public URL of the exported PDF.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        title=title,
        author="StoryForge Pro",
    )

    styles = getSampleStyleSheet()
    story = []

    # Title page
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph(f"<b>{title}</b>", styles["Title"]))
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph("Generated by StoryForge Pro", styles["Normal"]))
    story.append(PageBreak())

    for page in pages:
        for panel in page.panels:
            # Try to download and embed the image
            img_bytes = await _download_image(panel.image_url)
            if img_bytes:
                img = Image(ImageReader(io.BytesIO(img_bytes)))
                img.drawWidth = 6 * inch
                img.drawHeight = 4.5 * inch
                story.append(img)
            else:
                story.append(Paragraph(
                    f"[Panel {panel.panel_number}: {panel.prompt_used[:100]}...]",
                    styles["Normal"],
                ))

            # Dialogue overlay
            if panel.dialogue_overlay:
                story.append(Spacer(1, 0.1 * inch))
                story.append(Paragraph(
                    f"<i>{panel.dialogue_overlay}</i>",
                    styles["Normal"],
                ))

            # Caption
            if panel.caption:
                story.append(Paragraph(panel.caption, styles["Normal"]))

            story.append(Spacer(1, 0.3 * inch))

        story.append(PageBreak())

    doc.build(story)
    pdf_bytes = buffer.getvalue()

    url = await upload_export(
        file_bytes=pdf_bytes,
        project_id=project_id,
        format="pdf",
        content_type="application/pdf",
    )
    return url


# ── CBZ Export ─────────────────────────────────────────────────────────────

async def export_cbz(
    pages: list[PanelPage],
    project_id: str,
) -> str:
    """Export panels as a CBZ comic archive.

    CBZ is just a ZIP of images. Simple, but universally supported
    by comic readers.

    Returns:
        Public URL of the exported CBZ.
    """
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        img_index = 0
        for page in pages:
            for panel in page.panels:
                img_bytes = await _download_image(panel.image_url)
                if img_bytes:
                    filename = f"{img_index:04d}_{panel.panel_id}.png"
                    zf.writestr(filename, img_bytes)
                    img_index += 1

    cbz_bytes = buffer.getvalue()

    url = await upload_export(
        file_bytes=cbz_bytes,
        project_id=project_id,
        format="cbz",
        content_type="application/x-cbz",
    )
    return url


# ── PPTX Export ────────────────────────────────────────────────────────────

async def export_pptx(
    pages: list[PanelPage],
    project_id: str,
    title: str = "StoryForge Pro",
) -> str:
    """Export storyboard as a PowerPoint pitch deck.

    Each panel gets a slide with the image and notes.
    Perfect for pitching to studios.

    Returns:
        Public URL of the exported PPTX.
    """
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Title slide
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by StoryForge Pro"

    # Panel slides
    blank_layout = prs.slide_layouts[6]  # Blank
    for page in pages:
        for panel in page.panels:
            slide = prs.slides.add_slide(blank_layout)

            img_bytes = await _download_image(panel.image_url)
            if img_bytes:
                img_stream = io.BytesIO(img_bytes)
                slide.shapes.add_picture(
                    img_stream,
                    Inches(0.5),
                    Inches(0.5),
                    Inches(8),
                    Inches(6),
                )

            # Add text box for dialogue/notes
            if panel.dialogue_overlay or panel.caption:
                from pptx.util import Inches, Pt
                txBox = slide.shapes.add_textbox(
                    Inches(9), Inches(1), Inches(3.8), Inches(5)
                )
                tf = txBox.text_frame
                tf.word_wrap = True

                if panel.dialogue_overlay:
                    p = tf.paragraphs[0]
                    p.text = panel.dialogue_overlay
                    p.font.size = Pt(14)

                if panel.caption:
                    p = tf.add_paragraph()
                    p.text = panel.caption
                    p.font.size = Pt(12)
                    p.font.italic = True

    buffer = io.BytesIO()
    prs.save(buffer)
    pptx_bytes = buffer.getvalue()

    url = await upload_export(
        file_bytes=pptx_bytes,
        project_id=project_id,
        format="pptx",
        content_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
    )
    return url
