import { useEffect, useState } from 'react';
import { useGenerationStore } from '../../stores/generationStore';
import type { OutputMode } from '../../types';

const T = {
  gold: '#D4A843', goldLight: '#F0D78C', goldBright: '#FFF1B8',
  bg: '#0a0a0a', dim: '#888',
};

const TIPS = [
  'Each panel is uniquely generated by AI',
  'StoryForge Pro uses Gemini for visual storytelling',
  'Your scenes are being brought to life',
  'AI is crafting each frame with care',
  'Almost there — great stories take a moment',
];

interface Props {
  mode: OutputMode;
}

export function GeneratingOverlay({ mode }: Props) {
  const [tipIdx, setTipIdx] = useState(0);
  const [dots, setDots] = useState('');
  const { overallProgress, currentPhase } = useGenerationStore();

  useEffect(() => {
    const interval = setInterval(() => {
      setTipIdx((i) => (i + 1) % TIPS.length);
    }, 7000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
      setDots((d) => d.length >= 3 ? '' : d + '.');
    }, 500);
    return () => clearInterval(interval);
  }, []);

  // Parse page/panel info from currentPhase message
  const progressText = currentPhase || 'Starting generation...';
  const progressPct = Math.min(overallProgress, 100);

  const modeLabel = mode === 'comic' ? 'Comic' : mode === 'manga' ? 'Manga'
    : mode === 'storyboard' ? 'Storyboard' : 'Trailer';

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 1000,
      background: 'rgba(0,0,0,0.85)',
      backdropFilter: 'blur(12px)',
      display: 'flex', flexDirection: 'column',
      alignItems: 'center', justifyContent: 'center',
      gap: 32,
    }}>
      {/* Animated rings */}
      <div style={{ position: 'relative', width: 160, height: 160 }}>
        <div style={{
          position: 'absolute', inset: 0,
          border: `3px solid rgba(212,168,67,0.1)`,
          borderTopColor: T.gold,
          borderRadius: '50%',
          animation: 'genSpin 2s linear infinite',
        }} />
        <div style={{
          position: 'absolute', inset: 16,
          border: `2px solid rgba(212,168,67,0.08)`,
          borderBottomColor: T.goldLight,
          borderRadius: '50%',
          animation: 'genSpin 3s linear infinite reverse',
        }} />
        <div style={{
          position: 'absolute', inset: 32,
          border: `2px solid rgba(212,168,67,0.06)`,
          borderLeftColor: T.goldBright,
          borderRadius: '50%',
          animation: 'genSpin 1.5s linear infinite',
        }} />
        <div style={{
          position: 'absolute', inset: 0,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          flexDirection: 'column',
        }}>
          {/* Progress percentage in center */}
          <span style={{
            fontSize: 28, fontWeight: 800,
            background: `linear-gradient(135deg, ${T.goldBright}, ${T.gold})`,
            WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text',
          }}>
            {progressPct > 0 ? `${progressPct}%` : '⚡'}
          </span>
        </div>

        {[0, 1, 2, 3, 4, 5].map((i) => (
          <div key={i} style={{
            position: 'absolute',
            width: 6, height: 6, borderRadius: '50%',
            background: T.gold,
            opacity: 0.4 + (i * 0.1),
            top: '50%', left: '50%',
            animation: `genOrbit ${3 + i * 0.5}s linear infinite`,
            animationDelay: `${i * -0.5}s`,
            transformOrigin: `${-60 - i * 5}px 0`,
          }} />
        ))}
      </div>

      {/* Status — shows real progress from WebSocket */}
      <div style={{ textAlign: 'center', maxWidth: 400 }}>
        <p style={{
          fontSize: 13, fontWeight: 600,
          color: T.goldBright, letterSpacing: '0.08em',
          textTransform: 'uppercase', marginBottom: 8,
        }}>
          Generating {modeLabel}
        </p>
        <p style={{
          fontSize: 18, fontWeight: 700,
          background: `linear-gradient(135deg, ${T.goldBright}, ${T.goldLight}, ${T.gold})`,
          WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text',
          marginBottom: 8,
        }}>
          {progressText}{dots}
        </p>
        <p style={{
          fontSize: 12, color: T.dim, maxWidth: 300, margin: '0 auto',
          animation: 'genFadeSwap 7s ease-in-out infinite',
        }}>
          💡 {TIPS[tipIdx]}
        </p>
      </div>

      {/* Real progress bar */}
      <div style={{
        width: 280, height: 4, borderRadius: 2,
        background: 'rgba(212,168,67,0.15)',
        overflow: 'hidden',
      }}>
        {progressPct > 0 ? (
          <div style={{
            width: `${progressPct}%`, height: '100%',
            background: `linear-gradient(90deg, ${T.gold}, ${T.goldBright})`,
            borderRadius: 2,
            transition: 'width 0.5s ease-out',
          }} />
        ) : (
          <div style={{
            width: '30%', height: '100%',
            background: `linear-gradient(90deg, ${T.gold}, ${T.goldBright})`,
            borderRadius: 2,
            animation: 'genProgress 2s ease-in-out infinite',
          }} />
        )}
      </div>

      <style>{`
        @keyframes genSpin {
          to { transform: rotate(360deg); }
        }
        @keyframes genOrbit {
          to { transform: rotate(360deg); }
        }
        @keyframes genProgress {
          0% { transform: translateX(-100%); }
          100% { transform: translateX(400%); }
        }
        @keyframes genFadeSwap {
          0%, 90%, 100% { opacity: 1; }
          95% { opacity: 0.3; }
        }
      `}</style>
    </div>
  );
}
